### ISSUE TITLE
Allo specifying parsers with  a simple map

### ISSUE THREAD

**Issue by retog** [rdf-ext/rdf-store-ldp#4]
The following constructor invocation should work again:

```
var store = new LdpStore({
parsers : {
'text/turtle' : rdf.parseTurtle
}
});
```

From the perspective of the API user there' no advantage in having to pass an `ParserUtil`instance rather than just a map.

**Comment by bergos** [comment]
Fixed in latest [commit](https://github.com/rdf-ext/rdf-store-ldp/commit/687f242ebe1f496ca5327c2533621584ddf0aca3).
